"""Model update

Revision ID: 1f21fb1a706f
Revises: cc53f0661511
Create Date: 2023-11-09 23:40:28.915440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f21fb1a706f'
down_revision = 'cc53f0661511'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
