"""Empty init

Revision ID: 1fb0ed7989c0
Revises: 6251d4ce0167
Create Date: 2023-11-07 16:05:32.040981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb0ed7989c0'
down_revision = '6251d4ce0167'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
