"""model relationship update

Revision ID: 29c346391e13
Revises: 1fb0ed7989c0
Create Date: 2023-11-09 23:10:08.128361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c346391e13'
down_revision = '1fb0ed7989c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
