"""model relationship update

Revision ID: cc53f0661511
Revises: 29c346391e13
Create Date: 2023-11-09 23:11:09.753211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc53f0661511'
down_revision = '29c346391e13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_reviews',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'review_id')
    )
    op.add_column('reviews', sa.Column('the_review', sa.String(), nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.VARCHAR(), nullable=True))
    op.drop_column('reviews', 'the_review')
    op.drop_table('customer_reviews')
    # ### end Alembic commands ###
